sudo: required

language: python

python:
  - "3.6"

before_install:
  - sudo apt-get install libmysqlclient-dev
  - cd mbtb_app/resources/apis/user_registration
  - pip install -r requirements.txt

script:
  - python3 manage.py test

skip_cleanup: true