sudo: required
dist: bionic

services:
  - mysql

matrix:
  include:
    - language: python
      python: 3.6

      before_install:
        - mysql -u root -e "CREATE USER 'test'@'localhost' IDENTIFIED BY 'test@123';"
        - mysql -u root -e "GRANT ALL PRIVILEGES ON * . * TO 'test'@'localhost';"
        - sudo apt-get install libmysqlclient-dev
        - cd mbtb_app/resources/apis/users
        - pip install -r requirements.txt

      script:
        - python3 manage.py test

      after_success:
        - python3 manage.py runserver

    - language: python
      python: 3.6

      before_install:
        - mysql -u root -e "CREATE USER 'test'@'localhost' IDENTIFIED BY 'test@123';"
        - mysql -u root -e "GRANT ALL PRIVILEGES ON * . * TO 'test'@'localhost';"
        - sudo apt-get install libmysqlclient-dev
        - cd mbtb_app/resources/apis/data
        - cd ../data
        - pip install -r requirements.txt

        script:
          - python3 manage.py test

        after_success:
          - python3 manage.py runserver 9000


    - language: node_js
      node_js:
        - "node"
      before_install:
        - cd mbtb_app/web_portal/mbtb_portal
      install:
        - npm install
      script:
        - npm test
